### ISSUE TITLE
Link problem

### ISSUE THREAD

**Issue by FlashPapa** [artf/grapesjs-mjml#7]
The link management does not work, when you put a link on text it works randomly and does not update the code mjml;
The problem also exists on [demo mjml](http://grapesjs.com/demo-mjml.html).
For this to work you must reselect the text with the link and the mjml code has been updated !?

**Comment by artf** [comment]
thanks for the catch @FlashPapa do you encounter the issue only with CKEditor plugin?

**Comment by FlashPapa** [comment]
Hello, for the moment I only used ckeditor.
Thank you

**Comment by FlashPapa** [comment]
the problem is solved !

**Comment by NorthstarTech** [comment]
I am using the ckeditor with mjml. On creating the link, the selected text loses its position and always put the text on the first. Help and solution needed. 
Thanks

**Comment by izaa** [comment]
@FlashPapa what solve this? Still cant add link href in mjml basic rte.
